spring:
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  datasource:
    url: jdbc:h2:mem:sample;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
  logging.level:
    org.hibernate.SQL: debug